// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: Game.Common.proto

package Game_Common

import (
	encoding_binary "encoding/binary"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// 主命令.
type MAINID int32

const (
	MAINID_MAIN_MESSAGE_CLIENT_ID_BEGIN       MAINID = 0
	MAINID_MAIN_MESSAGE_CLIENT_TO_PROXY       MAINID = 1
	MAINID_MAIN_MESSAGE_CLIENT_TO_HALL        MAINID = 2
	MAINID_MAIN_MESSAGE_CLIENT_TO_GAME_SERVER MAINID = 3
	MAINID_MAIN_MESSAGE_CLIENT_TO_GAME_LOGIC  MAINID = 4
	MAINID_MAIN_MESSAGE_PROXY_TO_HALL         MAINID = 5
	MAINID_MAIN_MESSAGE_HALL_TO_PROXY         MAINID = 6
	MAINID_MAIN_MESSAGE_PROXY_TO_GAME_SERVER  MAINID = 7
	MAINID_MAIN_MESSAGE_GAME_SERVER_TO_PROXY  MAINID = 8
)

var MAINID_name = map[int32]string{
	0: "MAIN_MESSAGE_CLIENT_ID_BEGIN",
	1: "MAIN_MESSAGE_CLIENT_TO_PROXY",
	2: "MAIN_MESSAGE_CLIENT_TO_HALL",
	3: "MAIN_MESSAGE_CLIENT_TO_GAME_SERVER",
	4: "MAIN_MESSAGE_CLIENT_TO_GAME_LOGIC",
	5: "MAIN_MESSAGE_PROXY_TO_HALL",
	6: "MAIN_MESSAGE_HALL_TO_PROXY",
	7: "MAIN_MESSAGE_PROXY_TO_GAME_SERVER",
	8: "MAIN_MESSAGE_GAME_SERVER_TO_PROXY",
}

var MAINID_value = map[string]int32{
	"MAIN_MESSAGE_CLIENT_ID_BEGIN":       0,
	"MAIN_MESSAGE_CLIENT_TO_PROXY":       1,
	"MAIN_MESSAGE_CLIENT_TO_HALL":        2,
	"MAIN_MESSAGE_CLIENT_TO_GAME_SERVER": 3,
	"MAIN_MESSAGE_CLIENT_TO_GAME_LOGIC":  4,
	"MAIN_MESSAGE_PROXY_TO_HALL":         5,
	"MAIN_MESSAGE_HALL_TO_PROXY":         6,
	"MAIN_MESSAGE_PROXY_TO_GAME_SERVER":  7,
	"MAIN_MESSAGE_GAME_SERVER_TO_PROXY":  8,
}

func (x MAINID) String() string {
	return proto.EnumName(MAINID_name, int32(x))
}

func (MAINID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7b44c1ecc827cc2c, []int{0}
}

type MESSAGE_CLIENT_TO_SERVER_SUBID int32

const (
	MESSAGE_CLIENT_TO_SERVER_SUBID_MESSAGE_CLIENT_TO_SERVER_SUBID_BEGIN MESSAGE_CLIENT_TO_SERVER_SUBID = 0
	MESSAGE_CLIENT_TO_SERVER_SUBID_KEEP_ALIVE_REQ                       MESSAGE_CLIENT_TO_SERVER_SUBID = 1
	MESSAGE_CLIENT_TO_SERVER_SUBID_KEEP_ALIVE_RES                       MESSAGE_CLIENT_TO_SERVER_SUBID = 2
)

var MESSAGE_CLIENT_TO_SERVER_SUBID_name = map[int32]string{
	0: "MESSAGE_CLIENT_TO_SERVER_SUBID_BEGIN",
	1: "KEEP_ALIVE_REQ",
	2: "KEEP_ALIVE_RES",
}

var MESSAGE_CLIENT_TO_SERVER_SUBID_value = map[string]int32{
	"MESSAGE_CLIENT_TO_SERVER_SUBID_BEGIN": 0,
	"KEEP_ALIVE_REQ":                       1,
	"KEEP_ALIVE_RES":                       2,
}

func (x MESSAGE_CLIENT_TO_SERVER_SUBID) String() string {
	return proto.EnumName(MESSAGE_CLIENT_TO_SERVER_SUBID_name, int32(x))
}

func (MESSAGE_CLIENT_TO_SERVER_SUBID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7b44c1ecc827cc2c, []int{1}
}

type MESSAGE_CLIENT_TO_PROXY_SUBID int32

const (
	MESSAGE_CLIENT_TO_PROXY_SUBID_MESSAGE_CLIENT_TO_PROXY_SUBID_BEGIN              MESSAGE_CLIENT_TO_PROXY_SUBID = 0
	MESSAGE_CLIENT_TO_PROXY_SUBID_CLIENT_TO_PROXY_GET_AES_KEY_MESSAGE_REQ          MESSAGE_CLIENT_TO_PROXY_SUBID = 3
	MESSAGE_CLIENT_TO_PROXY_SUBID_CLIENT_TO_PROXY_GET_AES_KEY_MESSAGE_RES          MESSAGE_CLIENT_TO_PROXY_SUBID = 4
	MESSAGE_CLIENT_TO_PROXY_SUBID_CLIENT_TO_PROXY_BIND_USER_CONNECTION_MESSAGE_REQ MESSAGE_CLIENT_TO_PROXY_SUBID = 5
	MESSAGE_CLIENT_TO_PROXY_SUBID_CLIENT_TO_PROXY_BIND_USER_CONNECTION_MESSAGE_RES MESSAGE_CLIENT_TO_PROXY_SUBID = 6
	MESSAGE_CLIENT_TO_PROXY_SUBID_CLIENT_TO_PROXY_BIND_GAME_SERVER_MESSAGE_REQ     MESSAGE_CLIENT_TO_PROXY_SUBID = 7
	MESSAGE_CLIENT_TO_PROXY_SUBID_CLIENT_TO_PROXY_BIND_GAME_SERVER_MESSAGE_RES     MESSAGE_CLIENT_TO_PROXY_SUBID = 8
	MESSAGE_CLIENT_TO_PROXY_SUBID_PROXY_NOTIFY_SHUTDOWN_USER_CLIENT_MESSAGE_REQ    MESSAGE_CLIENT_TO_PROXY_SUBID = 9
)

var MESSAGE_CLIENT_TO_PROXY_SUBID_name = map[int32]string{
	0: "MESSAGE_CLIENT_TO_PROXY_SUBID_BEGIN",
	3: "CLIENT_TO_PROXY_GET_AES_KEY_MESSAGE_REQ",
	4: "CLIENT_TO_PROXY_GET_AES_KEY_MESSAGE_RES",
	5: "CLIENT_TO_PROXY_BIND_USER_CONNECTION_MESSAGE_REQ",
	6: "CLIENT_TO_PROXY_BIND_USER_CONNECTION_MESSAGE_RES",
	7: "CLIENT_TO_PROXY_BIND_GAME_SERVER_MESSAGE_REQ",
	8: "CLIENT_TO_PROXY_BIND_GAME_SERVER_MESSAGE_RES",
	9: "PROXY_NOTIFY_SHUTDOWN_USER_CLIENT_MESSAGE_REQ",
}

var MESSAGE_CLIENT_TO_PROXY_SUBID_value = map[string]int32{
	"MESSAGE_CLIENT_TO_PROXY_SUBID_BEGIN":              0,
	"CLIENT_TO_PROXY_GET_AES_KEY_MESSAGE_REQ":          3,
	"CLIENT_TO_PROXY_GET_AES_KEY_MESSAGE_RES":          4,
	"CLIENT_TO_PROXY_BIND_USER_CONNECTION_MESSAGE_REQ": 5,
	"CLIENT_TO_PROXY_BIND_USER_CONNECTION_MESSAGE_RES": 6,
	"CLIENT_TO_PROXY_BIND_GAME_SERVER_MESSAGE_REQ":     7,
	"CLIENT_TO_PROXY_BIND_GAME_SERVER_MESSAGE_RES":     8,
	"PROXY_NOTIFY_SHUTDOWN_USER_CLIENT_MESSAGE_REQ":    9,
}

func (x MESSAGE_CLIENT_TO_PROXY_SUBID) String() string {
	return proto.EnumName(MESSAGE_CLIENT_TO_PROXY_SUBID_name, int32(x))
}

func (MESSAGE_CLIENT_TO_PROXY_SUBID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7b44c1ecc827cc2c, []int{2}
}

type MESSAGE_CLIENT_TO_HALL_SUBID int32

const (
	MESSAGE_CLIENT_TO_HALL_SUBID_MESSAGE_CLIENT_TO_HALL_SUBID_BEGIN               MESSAGE_CLIENT_TO_HALL_SUBID = 0
	MESSAGE_CLIENT_TO_HALL_SUBID_CLIENT_TO_HALL_LOGIN_MESSAGE_REQ                 MESSAGE_CLIENT_TO_HALL_SUBID = 3
	MESSAGE_CLIENT_TO_HALL_SUBID_CLIENT_TO_HALL_LOGIN_MESSAGE_RES                 MESSAGE_CLIENT_TO_HALL_SUBID = 4
	MESSAGE_CLIENT_TO_HALL_SUBID_CLIENT_TO_HALL_GET_GAME_ROOM_INFO_REQ            MESSAGE_CLIENT_TO_HALL_SUBID = 5
	MESSAGE_CLIENT_TO_HALL_SUBID_CLIENT_TO_HALL_GET_GAME_ROOM_INFO_RES            MESSAGE_CLIENT_TO_HALL_SUBID = 6
	MESSAGE_CLIENT_TO_HALL_SUBID_CLIENT_TO_HALL_GET_GAME_SERVER_MESSAGE_REQ       MESSAGE_CLIENT_TO_HALL_SUBID = 7
	MESSAGE_CLIENT_TO_HALL_SUBID_CLIENT_TO_HALL_GET_GAME_SERVER_MESSAGE_RES       MESSAGE_CLIENT_TO_HALL_SUBID = 8
	MESSAGE_CLIENT_TO_HALL_SUBID_CLIENT_TO_HALL_GET_PLAYING_GAME_INFO_MESSAGE_REQ MESSAGE_CLIENT_TO_HALL_SUBID = 9
	MESSAGE_CLIENT_TO_HALL_SUBID_CLIENT_TO_HALL_GET_PLAYING_GAME_INFO_MESSAGE_RES MESSAGE_CLIENT_TO_HALL_SUBID = 10
	MESSAGE_CLIENT_TO_HALL_SUBID_CLIENT_TO_HALL_SET_HEAD_MESSAGE_REQ              MESSAGE_CLIENT_TO_HALL_SUBID = 11
	MESSAGE_CLIENT_TO_HALL_SUBID_CLIENT_TO_HALL_SET_HEAD_MESSAGE_RES              MESSAGE_CLIENT_TO_HALL_SUBID = 12
	MESSAGE_CLIENT_TO_HALL_SUBID_CLIENT_TO_HALL_SET_NICKNAME_MESSAGE_REQ          MESSAGE_CLIENT_TO_HALL_SUBID = 13
	MESSAGE_CLIENT_TO_HALL_SUBID_CLIENT_TO_HALL_SET_NICKNAME_MESSAGE_RES          MESSAGE_CLIENT_TO_HALL_SUBID = 14
	MESSAGE_CLIENT_TO_HALL_SUBID_CLIENT_TO_HALL_GET_USER_SCORE_MESSAGE_REQ        MESSAGE_CLIENT_TO_HALL_SUBID = 15
	MESSAGE_CLIENT_TO_HALL_SUBID_CLIENT_TO_HALL_GET_USER_SCORE_MESSAGE_RES        MESSAGE_CLIENT_TO_HALL_SUBID = 16
)

var MESSAGE_CLIENT_TO_HALL_SUBID_name = map[int32]string{
	0:  "MESSAGE_CLIENT_TO_HALL_SUBID_BEGIN",
	3:  "CLIENT_TO_HALL_LOGIN_MESSAGE_REQ",
	4:  "CLIENT_TO_HALL_LOGIN_MESSAGE_RES",
	5:  "CLIENT_TO_HALL_GET_GAME_ROOM_INFO_REQ",
	6:  "CLIENT_TO_HALL_GET_GAME_ROOM_INFO_RES",
	7:  "CLIENT_TO_HALL_GET_GAME_SERVER_MESSAGE_REQ",
	8:  "CLIENT_TO_HALL_GET_GAME_SERVER_MESSAGE_RES",
	9:  "CLIENT_TO_HALL_GET_PLAYING_GAME_INFO_MESSAGE_REQ",
	10: "CLIENT_TO_HALL_GET_PLAYING_GAME_INFO_MESSAGE_RES",
	11: "CLIENT_TO_HALL_SET_HEAD_MESSAGE_REQ",
	12: "CLIENT_TO_HALL_SET_HEAD_MESSAGE_RES",
	13: "CLIENT_TO_HALL_SET_NICKNAME_MESSAGE_REQ",
	14: "CLIENT_TO_HALL_SET_NICKNAME_MESSAGE_RES",
	15: "CLIENT_TO_HALL_GET_USER_SCORE_MESSAGE_REQ",
	16: "CLIENT_TO_HALL_GET_USER_SCORE_MESSAGE_RES",
}

var MESSAGE_CLIENT_TO_HALL_SUBID_value = map[string]int32{
	"MESSAGE_CLIENT_TO_HALL_SUBID_BEGIN":               0,
	"CLIENT_TO_HALL_LOGIN_MESSAGE_REQ":                 3,
	"CLIENT_TO_HALL_LOGIN_MESSAGE_RES":                 4,
	"CLIENT_TO_HALL_GET_GAME_ROOM_INFO_REQ":            5,
	"CLIENT_TO_HALL_GET_GAME_ROOM_INFO_RES":            6,
	"CLIENT_TO_HALL_GET_GAME_SERVER_MESSAGE_REQ":       7,
	"CLIENT_TO_HALL_GET_GAME_SERVER_MESSAGE_RES":       8,
	"CLIENT_TO_HALL_GET_PLAYING_GAME_INFO_MESSAGE_REQ": 9,
	"CLIENT_TO_HALL_GET_PLAYING_GAME_INFO_MESSAGE_RES": 10,
	"CLIENT_TO_HALL_SET_HEAD_MESSAGE_REQ":              11,
	"CLIENT_TO_HALL_SET_HEAD_MESSAGE_RES":              12,
	"CLIENT_TO_HALL_SET_NICKNAME_MESSAGE_REQ":          13,
	"CLIENT_TO_HALL_SET_NICKNAME_MESSAGE_RES":          14,
	"CLIENT_TO_HALL_GET_USER_SCORE_MESSAGE_REQ":        15,
	"CLIENT_TO_HALL_GET_USER_SCORE_MESSAGE_RES":        16,
}

func (x MESSAGE_CLIENT_TO_HALL_SUBID) String() string {
	return proto.EnumName(MESSAGE_CLIENT_TO_HALL_SUBID_name, int32(x))
}

func (MESSAGE_CLIENT_TO_HALL_SUBID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7b44c1ecc827cc2c, []int{3}
}

type MESSAGE_CLIENT_TO_GAME_SERVER_SUBID int32

const (
	MESSAGE_CLIENT_TO_GAME_SERVER_SUBID_A MESSAGE_CLIENT_TO_GAME_SERVER_SUBID = 0
)

var MESSAGE_CLIENT_TO_GAME_SERVER_SUBID_name = map[int32]string{
	0: "A",
}

var MESSAGE_CLIENT_TO_GAME_SERVER_SUBID_value = map[string]int32{
	"A": 0,
}

func (x MESSAGE_CLIENT_TO_GAME_SERVER_SUBID) String() string {
	return proto.EnumName(MESSAGE_CLIENT_TO_GAME_SERVER_SUBID_name, int32(x))
}

func (MESSAGE_CLIENT_TO_GAME_SERVER_SUBID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7b44c1ecc827cc2c, []int{4}
}

type MESSAGE_CLIENT_TO_GAME_LOGIC_SUBID int32

const (
	MESSAGE_CLIENT_TO_GAME_LOGIC_SUBID_B MESSAGE_CLIENT_TO_GAME_LOGIC_SUBID = 0
)

var MESSAGE_CLIENT_TO_GAME_LOGIC_SUBID_name = map[int32]string{
	0: "B",
}

var MESSAGE_CLIENT_TO_GAME_LOGIC_SUBID_value = map[string]int32{
	"B": 0,
}

func (x MESSAGE_CLIENT_TO_GAME_LOGIC_SUBID) String() string {
	return proto.EnumName(MESSAGE_CLIENT_TO_GAME_LOGIC_SUBID_name, int32(x))
}

func (MESSAGE_CLIENT_TO_GAME_LOGIC_SUBID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7b44c1ecc827cc2c, []int{5}
}

type MESSAGE_PROXY_TO_HALL_SUBID int32

const (
	MESSAGE_PROXY_TO_HALL_SUBID_HALL_ON_USER_OFFLINE MESSAGE_PROXY_TO_HALL_SUBID = 0
)

var MESSAGE_PROXY_TO_HALL_SUBID_name = map[int32]string{
	0: "HALL_ON_USER_OFFLINE",
}

var MESSAGE_PROXY_TO_HALL_SUBID_value = map[string]int32{
	"HALL_ON_USER_OFFLINE": 0,
}

func (x MESSAGE_PROXY_TO_HALL_SUBID) String() string {
	return proto.EnumName(MESSAGE_PROXY_TO_HALL_SUBID_name, int32(x))
}

func (MESSAGE_PROXY_TO_HALL_SUBID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7b44c1ecc827cc2c, []int{6}
}

type MESSAGE_HALL_TO_PROXY_SUBID int32

const (
	MESSAGE_HALL_TO_PROXY_SUBID_D MESSAGE_HALL_TO_PROXY_SUBID = 0
)

var MESSAGE_HALL_TO_PROXY_SUBID_name = map[int32]string{
	0: "D",
}

var MESSAGE_HALL_TO_PROXY_SUBID_value = map[string]int32{
	"D": 0,
}

func (x MESSAGE_HALL_TO_PROXY_SUBID) String() string {
	return proto.EnumName(MESSAGE_HALL_TO_PROXY_SUBID_name, int32(x))
}

func (MESSAGE_HALL_TO_PROXY_SUBID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7b44c1ecc827cc2c, []int{7}
}

type MESSAGE_PROXY_TO_GAME_SERVER_SUBID int32

const (
	MESSAGE_PROXY_TO_GAME_SERVER_SUBID_GAME_SERVER_ON_USER_OFFLINE MESSAGE_PROXY_TO_GAME_SERVER_SUBID = 0
)

var MESSAGE_PROXY_TO_GAME_SERVER_SUBID_name = map[int32]string{
	0: "GAME_SERVER_ON_USER_OFFLINE",
}

var MESSAGE_PROXY_TO_GAME_SERVER_SUBID_value = map[string]int32{
	"GAME_SERVER_ON_USER_OFFLINE": 0,
}

func (x MESSAGE_PROXY_TO_GAME_SERVER_SUBID) String() string {
	return proto.EnumName(MESSAGE_PROXY_TO_GAME_SERVER_SUBID_name, int32(x))
}

func (MESSAGE_PROXY_TO_GAME_SERVER_SUBID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7b44c1ecc827cc2c, []int{8}
}

type MESSAGE_GAME_SERVER_TO_PROXY_SUBID int32

const (
	MESSAGE_GAME_SERVER_TO_PROXY_SUBID_MESSAGE_GAME_SERVER_TO_PROXY_SUBID_BEGIN MESSAGE_GAME_SERVER_TO_PROXY_SUBID = 0
	MESSAGE_GAME_SERVER_TO_PROXY_SUBID_PROXY_NOTIFY_KILL_BOSS_MESSAGE_REQ       MESSAGE_GAME_SERVER_TO_PROXY_SUBID = 42
)

var MESSAGE_GAME_SERVER_TO_PROXY_SUBID_name = map[int32]string{
	0:  "MESSAGE_GAME_SERVER_TO_PROXY_SUBID_BEGIN",
	42: "PROXY_NOTIFY_KILL_BOSS_MESSAGE_REQ",
}

var MESSAGE_GAME_SERVER_TO_PROXY_SUBID_value = map[string]int32{
	"MESSAGE_GAME_SERVER_TO_PROXY_SUBID_BEGIN": 0,
	"PROXY_NOTIFY_KILL_BOSS_MESSAGE_REQ":       42,
}

func (x MESSAGE_GAME_SERVER_TO_PROXY_SUBID) String() string {
	return proto.EnumName(MESSAGE_GAME_SERVER_TO_PROXY_SUBID_name, int32(x))
}

func (MESSAGE_GAME_SERVER_TO_PROXY_SUBID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7b44c1ecc827cc2c, []int{9}
}

type KeepAliveMessageResponse_KeepAliveRetCode int32

const (
	KeepAliveMessageResponse_KEEPALIVE_OK      KeepAliveMessageResponse_KeepAliveRetCode = 0
	KeepAliveMessageResponse_KEEPALIVE_FAIL    KeepAliveMessageResponse_KeepAliveRetCode = 1
	KeepAliveMessageResponse_KEEPALIVE_RELOGIN KeepAliveMessageResponse_KeepAliveRetCode = 2
	KeepAliveMessageResponse_KEEPALIVE_UNKNOWN KeepAliveMessageResponse_KeepAliveRetCode = 20
)

var KeepAliveMessageResponse_KeepAliveRetCode_name = map[int32]string{
	0:  "KEEPALIVE_OK",
	1:  "KEEPALIVE_FAIL",
	2:  "KEEPALIVE_RELOGIN",
	20: "KEEPALIVE_UNKNOWN",
}

var KeepAliveMessageResponse_KeepAliveRetCode_value = map[string]int32{
	"KEEPALIVE_OK":      0,
	"KEEPALIVE_FAIL":    1,
	"KEEPALIVE_RELOGIN": 2,
	"KEEPALIVE_UNKNOWN": 20,
}

func (x KeepAliveMessageResponse_KeepAliveRetCode) String() string {
	return proto.EnumName(KeepAliveMessageResponse_KeepAliveRetCode_name, int32(x))
}

func (KeepAliveMessageResponse_KeepAliveRetCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7b44c1ecc827cc2c, []int{2, 0}
}

type Header struct {
	Sign int32 `protobuf:"varint,1,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b44c1ecc827cc2c, []int{0}
}
func (m *Header) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Header.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return m.Size()
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetSign() int32 {
	if m != nil {
		return m.Sign
	}
	return 0
}

type KeepAliveMessage struct {
	Header  *Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Session string  `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
}

func (m *KeepAliveMessage) Reset()         { *m = KeepAliveMessage{} }
func (m *KeepAliveMessage) String() string { return proto.CompactTextString(m) }
func (*KeepAliveMessage) ProtoMessage()    {}
func (*KeepAliveMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b44c1ecc827cc2c, []int{1}
}
func (m *KeepAliveMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KeepAliveMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KeepAliveMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KeepAliveMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeepAliveMessage.Merge(m, src)
}
func (m *KeepAliveMessage) XXX_Size() int {
	return m.Size()
}
func (m *KeepAliveMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_KeepAliveMessage.DiscardUnknown(m)
}

var xxx_messageInfo_KeepAliveMessage proto.InternalMessageInfo

func (m *KeepAliveMessage) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *KeepAliveMessage) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

type KeepAliveMessageResponse struct {
	Header   *Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	RetCode  int32   `protobuf:"varint,2,opt,name=retCode,proto3" json:"retCode,omitempty"`
	ErrorMsg string  `protobuf:"bytes,3,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (m *KeepAliveMessageResponse) Reset()         { *m = KeepAliveMessageResponse{} }
func (m *KeepAliveMessageResponse) String() string { return proto.CompactTextString(m) }
func (*KeepAliveMessageResponse) ProtoMessage()    {}
func (*KeepAliveMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b44c1ecc827cc2c, []int{2}
}
func (m *KeepAliveMessageResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KeepAliveMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KeepAliveMessageResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KeepAliveMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeepAliveMessageResponse.Merge(m, src)
}
func (m *KeepAliveMessageResponse) XXX_Size() int {
	return m.Size()
}
func (m *KeepAliveMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KeepAliveMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KeepAliveMessageResponse proto.InternalMessageInfo

func (m *KeepAliveMessageResponse) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *KeepAliveMessageResponse) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *KeepAliveMessageResponse) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

type ProxyNotifyRechargeScoreMessage struct {
	Header  *Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	UserId  int32   `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Id      int32   `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	OrderId string  `protobuf:"bytes,4,opt,name=orderId,proto3" json:"orderId,omitempty"`
	RealPay float64 `protobuf:"fixed64,5,opt,name=realPay,proto3" json:"realPay,omitempty"`
	Status  int32   `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
}

func (m *ProxyNotifyRechargeScoreMessage) Reset()         { *m = ProxyNotifyRechargeScoreMessage{} }
func (m *ProxyNotifyRechargeScoreMessage) String() string { return proto.CompactTextString(m) }
func (*ProxyNotifyRechargeScoreMessage) ProtoMessage()    {}
func (*ProxyNotifyRechargeScoreMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b44c1ecc827cc2c, []int{3}
}
func (m *ProxyNotifyRechargeScoreMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProxyNotifyRechargeScoreMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProxyNotifyRechargeScoreMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProxyNotifyRechargeScoreMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyNotifyRechargeScoreMessage.Merge(m, src)
}
func (m *ProxyNotifyRechargeScoreMessage) XXX_Size() int {
	return m.Size()
}
func (m *ProxyNotifyRechargeScoreMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyNotifyRechargeScoreMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyNotifyRechargeScoreMessage proto.InternalMessageInfo

func (m *ProxyNotifyRechargeScoreMessage) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ProxyNotifyRechargeScoreMessage) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ProxyNotifyRechargeScoreMessage) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProxyNotifyRechargeScoreMessage) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *ProxyNotifyRechargeScoreMessage) GetRealPay() float64 {
	if m != nil {
		return m.RealPay
	}
	return 0
}

func (m *ProxyNotifyRechargeScoreMessage) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type ProxyNotifyShutDownUserClientMessage struct {
	Header *Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	UserId int32   `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (m *ProxyNotifyShutDownUserClientMessage) Reset()         { *m = ProxyNotifyShutDownUserClientMessage{} }
func (m *ProxyNotifyShutDownUserClientMessage) String() string { return proto.CompactTextString(m) }
func (*ProxyNotifyShutDownUserClientMessage) ProtoMessage()    {}
func (*ProxyNotifyShutDownUserClientMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b44c1ecc827cc2c, []int{4}
}
func (m *ProxyNotifyShutDownUserClientMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProxyNotifyShutDownUserClientMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProxyNotifyShutDownUserClientMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProxyNotifyShutDownUserClientMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyNotifyShutDownUserClientMessage.Merge(m, src)
}
func (m *ProxyNotifyShutDownUserClientMessage) XXX_Size() int {
	return m.Size()
}
func (m *ProxyNotifyShutDownUserClientMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyNotifyShutDownUserClientMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyNotifyShutDownUserClientMessage proto.InternalMessageInfo

func (m *ProxyNotifyShutDownUserClientMessage) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ProxyNotifyShutDownUserClientMessage) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type ProxyNotifyKillBossMessage struct {
	Header *Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Msg    string  `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (m *ProxyNotifyKillBossMessage) Reset()         { *m = ProxyNotifyKillBossMessage{} }
func (m *ProxyNotifyKillBossMessage) String() string { return proto.CompactTextString(m) }
func (*ProxyNotifyKillBossMessage) ProtoMessage()    {}
func (*ProxyNotifyKillBossMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b44c1ecc827cc2c, []int{5}
}
func (m *ProxyNotifyKillBossMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProxyNotifyKillBossMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProxyNotifyKillBossMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProxyNotifyKillBossMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyNotifyKillBossMessage.Merge(m, src)
}
func (m *ProxyNotifyKillBossMessage) XXX_Size() int {
	return m.Size()
}
func (m *ProxyNotifyKillBossMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyNotifyKillBossMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyNotifyKillBossMessage proto.InternalMessageInfo

func (m *ProxyNotifyKillBossMessage) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ProxyNotifyKillBossMessage) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type ProxyNotifyReenterRoomMessage struct {
	Header *Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
}

func (m *ProxyNotifyReenterRoomMessage) Reset()         { *m = ProxyNotifyReenterRoomMessage{} }
func (m *ProxyNotifyReenterRoomMessage) String() string { return proto.CompactTextString(m) }
func (*ProxyNotifyReenterRoomMessage) ProtoMessage()    {}
func (*ProxyNotifyReenterRoomMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b44c1ecc827cc2c, []int{6}
}
func (m *ProxyNotifyReenterRoomMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProxyNotifyReenterRoomMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProxyNotifyReenterRoomMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProxyNotifyReenterRoomMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyNotifyReenterRoomMessage.Merge(m, src)
}
func (m *ProxyNotifyReenterRoomMessage) XXX_Size() int {
	return m.Size()
}
func (m *ProxyNotifyReenterRoomMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyNotifyReenterRoomMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyNotifyReenterRoomMessage proto.InternalMessageInfo

func (m *ProxyNotifyReenterRoomMessage) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

type HallNotifyReLoginServerMessage struct {
	Header *Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
}

func (m *HallNotifyReLoginServerMessage) Reset()         { *m = HallNotifyReLoginServerMessage{} }
func (m *HallNotifyReLoginServerMessage) String() string { return proto.CompactTextString(m) }
func (*HallNotifyReLoginServerMessage) ProtoMessage()    {}
func (*HallNotifyReLoginServerMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b44c1ecc827cc2c, []int{7}
}
func (m *HallNotifyReLoginServerMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HallNotifyReLoginServerMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HallNotifyReLoginServerMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HallNotifyReLoginServerMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HallNotifyReLoginServerMessage.Merge(m, src)
}
func (m *HallNotifyReLoginServerMessage) XXX_Size() int {
	return m.Size()
}
func (m *HallNotifyReLoginServerMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_HallNotifyReLoginServerMessage.DiscardUnknown(m)
}

var xxx_messageInfo_HallNotifyReLoginServerMessage proto.InternalMessageInfo

func (m *HallNotifyReLoginServerMessage) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func init() {
	proto.RegisterEnum("Game.Common.MAINID", MAINID_name, MAINID_value)
	proto.RegisterEnum("Game.Common.MESSAGE_CLIENT_TO_SERVER_SUBID", MESSAGE_CLIENT_TO_SERVER_SUBID_name, MESSAGE_CLIENT_TO_SERVER_SUBID_value)
	proto.RegisterEnum("Game.Common.MESSAGE_CLIENT_TO_PROXY_SUBID", MESSAGE_CLIENT_TO_PROXY_SUBID_name, MESSAGE_CLIENT_TO_PROXY_SUBID_value)
	proto.RegisterEnum("Game.Common.MESSAGE_CLIENT_TO_HALL_SUBID", MESSAGE_CLIENT_TO_HALL_SUBID_name, MESSAGE_CLIENT_TO_HALL_SUBID_value)
	proto.RegisterEnum("Game.Common.MESSAGE_CLIENT_TO_GAME_SERVER_SUBID", MESSAGE_CLIENT_TO_GAME_SERVER_SUBID_name, MESSAGE_CLIENT_TO_GAME_SERVER_SUBID_value)
	proto.RegisterEnum("Game.Common.MESSAGE_CLIENT_TO_GAME_LOGIC_SUBID", MESSAGE_CLIENT_TO_GAME_LOGIC_SUBID_name, MESSAGE_CLIENT_TO_GAME_LOGIC_SUBID_value)
	proto.RegisterEnum("Game.Common.MESSAGE_PROXY_TO_HALL_SUBID", MESSAGE_PROXY_TO_HALL_SUBID_name, MESSAGE_PROXY_TO_HALL_SUBID_value)
	proto.RegisterEnum("Game.Common.MESSAGE_HALL_TO_PROXY_SUBID", MESSAGE_HALL_TO_PROXY_SUBID_name, MESSAGE_HALL_TO_PROXY_SUBID_value)
	proto.RegisterEnum("Game.Common.MESSAGE_PROXY_TO_GAME_SERVER_SUBID", MESSAGE_PROXY_TO_GAME_SERVER_SUBID_name, MESSAGE_PROXY_TO_GAME_SERVER_SUBID_value)
	proto.RegisterEnum("Game.Common.MESSAGE_GAME_SERVER_TO_PROXY_SUBID", MESSAGE_GAME_SERVER_TO_PROXY_SUBID_name, MESSAGE_GAME_SERVER_TO_PROXY_SUBID_value)
	proto.RegisterEnum("Game.Common.KeepAliveMessageResponse_KeepAliveRetCode", KeepAliveMessageResponse_KeepAliveRetCode_name, KeepAliveMessageResponse_KeepAliveRetCode_value)
	proto.RegisterType((*Header)(nil), "Game.Common.Header")
	proto.RegisterType((*KeepAliveMessage)(nil), "Game.Common.KeepAliveMessage")
	proto.RegisterType((*KeepAliveMessageResponse)(nil), "Game.Common.KeepAliveMessageResponse")
	proto.RegisterType((*ProxyNotifyRechargeScoreMessage)(nil), "Game.Common.ProxyNotifyRechargeScoreMessage")
	proto.RegisterType((*ProxyNotifyShutDownUserClientMessage)(nil), "Game.Common.ProxyNotifyShutDownUserClientMessage")
	proto.RegisterType((*ProxyNotifyKillBossMessage)(nil), "Game.Common.ProxyNotifyKillBossMessage")
	proto.RegisterType((*ProxyNotifyReenterRoomMessage)(nil), "Game.Common.ProxyNotifyReenterRoomMessage")
	proto.RegisterType((*HallNotifyReLoginServerMessage)(nil), "Game.Common.HallNotifyReLoginServerMessage")
}

func init() { proto.RegisterFile("Game.Common.proto", fileDescriptor_7b44c1ecc827cc2c) }

var fileDescriptor_7b44c1ecc827cc2c = []byte{
	// 960 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0xdd, 0x72, 0xda, 0x46,
	0x14, 0xc7, 0x11, 0x36, 0xd8, 0x39, 0x4e, 0xdd, 0xcd, 0x36, 0xed, 0x30, 0xb6, 0x83, 0xa9, 0xea,
	0x24, 0x44, 0x76, 0x3c, 0xe9, 0xc7, 0x4c, 0xaf, 0x05, 0x2c, 0xa0, 0x41, 0xac, 0xa8, 0x16, 0x92,
	0x32, 0xbd, 0xd0, 0xd0, 0xb0, 0xc1, 0x9a, 0x02, 0xf2, 0x48, 0x38, 0xad, 0xfb, 0x14, 0x7d, 0x89,
	0xbe, 0x46, 0x2f, 0x7a, 0xd5, 0xe9, 0x55, 0x2e, 0x7b, 0xd9, 0xb1, 0xa7, 0xef, 0xd1, 0xd1, 0x07,
	0xfa, 0x00, 0xe1, 0xd8, 0x4c, 0xee, 0xb4, 0xbb, 0xbf, 0xf3, 0x3f, 0xe7, 0xec, 0xd9, 0x73, 0x00,
	0x1e, 0x34, 0x06, 0x13, 0x7e, 0x5a, 0xb5, 0x26, 0x13, 0x6b, 0x7a, 0x7a, 0x6e, 0x5b, 0x33, 0x0b,
	0xef, 0xc4, 0xb6, 0xc4, 0x03, 0xc8, 0x37, 0xf9, 0x60, 0xc8, 0x6d, 0x8c, 0x61, 0xd3, 0x31, 0x47,
	0xd3, 0x82, 0x50, 0x12, 0xca, 0x39, 0xdd, 0xfb, 0x16, 0xfb, 0x80, 0x5a, 0x9c, 0x9f, 0xcb, 0x63,
	0xf3, 0x2d, 0x6f, 0x73, 0xc7, 0x19, 0x8c, 0x38, 0x3e, 0x86, 0xfc, 0x99, 0x67, 0xe1, 0x91, 0x3b,
	0x5f, 0x7d, 0x72, 0x1a, 0x77, 0xe1, 0x8b, 0xe9, 0x01, 0x82, 0x0b, 0xb0, 0xe5, 0x70, 0xc7, 0x31,
	0xad, 0x69, 0x21, 0x5b, 0x12, 0xca, 0xf7, 0xf4, 0xf9, 0x52, 0xfc, 0x4f, 0x80, 0xc2, 0xa2, 0xb6,
	0xce, 0x9d, 0x73, 0x6b, 0xea, 0xdc, 0xdd, 0x87, 0xcd, 0x67, 0x55, 0x6b, 0xc8, 0x3d, 0x1f, 0x39,
	0x7d, 0xbe, 0xc4, 0x7b, 0xb0, 0xcd, 0x6d, 0xdb, 0xb2, 0xdb, 0xce, 0xa8, 0xb0, 0xe1, 0xb9, 0x0f,
	0xd7, 0xe2, 0x9b, 0x58, 0x6a, 0x7a, 0xc0, 0x23, 0xb8, 0xdf, 0x22, 0xa4, 0x23, 0xab, 0xca, 0x4b,
	0x62, 0x68, 0x2d, 0x94, 0xc1, 0x18, 0x76, 0xa3, 0x9d, 0xba, 0xac, 0xa8, 0x48, 0xc0, 0x9f, 0xc2,
	0x83, 0x68, 0x4f, 0x27, 0xaa, 0xd6, 0x50, 0x28, 0xca, 0x26, 0xb7, 0x7b, 0xb4, 0x45, 0xb5, 0x57,
	0x14, 0x3d, 0x14, 0xff, 0x14, 0xe0, 0xb0, 0x63, 0x5b, 0xbf, 0x5c, 0x52, 0x6b, 0x66, 0xbe, 0xb9,
	0xd4, 0xf9, 0xeb, 0xb3, 0x81, 0x3d, 0xe2, 0xec, 0xb5, 0x65, 0xaf, 0x77, 0xa5, 0x9f, 0x41, 0xfe,
	0xc2, 0xe1, 0xb6, 0x32, 0x0c, 0xb2, 0x0d, 0x56, 0x78, 0x17, 0xb2, 0xe6, 0xd0, 0x4b, 0x33, 0xa7,
	0x67, 0xcd, 0xa1, 0x7b, 0x2d, 0x96, 0x3d, 0xf4, 0xc0, 0x4d, 0xff, 0xea, 0x83, 0xa5, 0x7f, 0x61,
	0x83, 0x71, 0x67, 0x70, 0x59, 0xc8, 0x95, 0x84, 0xb2, 0xa0, 0xcf, 0x97, 0xae, 0xb6, 0x33, 0x1b,
	0xcc, 0x2e, 0x9c, 0x42, 0xde, 0xd7, 0xf6, 0x57, 0xe2, 0x4f, 0x70, 0x14, 0xcb, 0x81, 0x9d, 0x5d,
	0xcc, 0x6a, 0xd6, 0xcf, 0xd3, 0x9e, 0xc3, 0xed, 0xea, 0xd8, 0xe4, 0xd3, 0xd9, 0x87, 0x4c, 0x44,
	0xfc, 0x01, 0xf6, 0x62, 0xce, 0x5a, 0xe6, 0x78, 0x5c, 0xb1, 0x1c, 0x67, 0x2d, 0x17, 0x08, 0x36,
	0x26, 0xce, 0x28, 0x78, 0x7a, 0xee, 0xa7, 0xa8, 0xc2, 0xa3, 0x44, 0x35, 0xf8, 0x74, 0xc6, 0x6d,
	0xdd, 0xb2, 0x26, 0xeb, 0xe8, 0x8b, 0x6d, 0x28, 0x36, 0x07, 0xe3, 0xf1, 0x5c, 0x4c, 0xb5, 0x46,
	0xe6, 0x94, 0x71, 0xfb, 0x2d, 0xb7, 0xd7, 0x91, 0x93, 0xfe, 0xce, 0x42, 0xbe, 0x2d, 0x2b, 0x54,
	0xa9, 0xe1, 0x12, 0x1c, 0xb8, 0x5f, 0x46, 0x9b, 0x30, 0x26, 0x37, 0x88, 0x51, 0x55, 0x15, 0x42,
	0xbb, 0x86, 0x52, 0x33, 0x2a, 0xc4, 0x7d, 0x6f, 0x99, 0x55, 0x44, 0x57, 0x33, 0x3a, 0xba, 0xf6,
	0x7d, 0x1f, 0x09, 0xf8, 0x10, 0xf6, 0x57, 0x10, 0x4d, 0x59, 0x55, 0x51, 0x16, 0x3f, 0x01, 0x71,
	0x05, 0xd0, 0x90, 0xdb, 0xc4, 0x60, 0x44, 0x7f, 0x49, 0x74, 0xb4, 0x81, 0x1f, 0xc3, 0xe7, 0x37,
	0x71, 0x6e, 0x07, 0x54, 0xd1, 0x26, 0x2e, 0xc2, 0x5e, 0x02, 0xf3, 0xe2, 0x08, 0xdd, 0xe5, 0x96,
	0xce, 0xdd, 0xed, 0x28, 0xde, 0xfc, 0x92, 0x9b, 0xd0, 0x3e, 0x1e, 0xcd, 0xd6, 0x12, 0x16, 0x3b,
	0x8d, 0xd4, 0xb6, 0x25, 0x1b, 0x8a, 0xcb, 0xf1, 0x06, 0x18, 0xeb, 0x55, 0x94, 0x1a, 0x2e, 0xc3,
	0xd1, 0xcd, 0x44, 0x78, 0xd7, 0xc1, 0x18, 0x30, 0xe6, 0x3d, 0xff, 0x1d, 0x12, 0x96, 0xf6, 0x18,
	0xca, 0x4a, 0xbf, 0x6f, 0xc0, 0xa3, 0x15, 0xf5, 0x08, 0x7c, 0x3e, 0x85, 0x2f, 0x6e, 0x04, 0x42,
	0x97, 0xc7, 0xf0, 0x74, 0x11, 0x68, 0x90, 0xae, 0x21, 0x13, 0x66, 0xb4, 0x48, 0x3f, 0x4c, 0xde,
	0x8d, 0x65, 0xe3, 0xf6, 0x30, 0x43, 0x9b, 0xf8, 0x1b, 0x78, 0xb1, 0x08, 0x57, 0x14, 0x5a, 0x33,
	0x7a, 0x8c, 0xe8, 0x46, 0x55, 0xa3, 0x94, 0x54, 0xbb, 0x8a, 0x46, 0x13, 0x2e, 0x72, 0x6b, 0x58,
	0x31, 0x94, 0xc7, 0x2f, 0xe0, 0x24, 0xd5, 0x2a, 0x5e, 0xb3, 0xb8, 0x9f, 0xad, 0x3b, 0x5a, 0x30,
	0xb4, 0x8d, 0xbf, 0x84, 0xe7, 0x3e, 0x47, 0xb5, 0xae, 0x52, 0xef, 0x1b, 0xac, 0xd9, 0xeb, 0xd6,
	0xb4, 0x57, 0x34, 0x08, 0xcd, 0x17, 0x8b, 0x3b, 0xb9, 0x27, 0xfd, 0x91, 0x83, 0x83, 0xf4, 0xae,
	0x08, 0xca, 0xe4, 0x76, 0xc6, 0x0d, 0xe7, 0x61, 0x95, 0x8e, 0xa0, 0xb4, 0x70, 0xee, 0xfd, 0x1c,
	0x2c, 0x94, 0xe7, 0xfd, 0x94, 0x5b, 0x97, 0x67, 0xf0, 0x78, 0x81, 0x72, 0x6b, 0xe8, 0xe5, 0xad,
	0x6b, 0x5a, 0xdb, 0x50, 0x68, 0x5d, 0x0b, 0x8a, 0x71, 0x4b, 0xd4, 0xad, 0xc0, 0x29, 0x48, 0xab,
	0xd0, 0xd4, 0xfb, 0xbf, 0x0b, 0xef, 0xde, 0x7e, 0xe2, 0x5d, 0x84, 0x7c, 0x47, 0x95, 0xfb, 0x0a,
	0x6d, 0xf8, 0x76, 0x5e, 0x34, 0x89, 0x02, 0xac, 0x61, 0xc5, 0x10, 0xb8, 0xcd, 0xb3, 0x58, 0x0d,
	0xd2, 0x35, 0x9a, 0x44, 0xae, 0x25, 0xe4, 0x77, 0x6e, 0x07, 0x32, 0x74, 0x3f, 0xd9, 0x38, 0x21,
	0x48, 0x95, 0x6a, 0x8b, 0xba, 0x31, 0xc4, 0x55, 0x3f, 0xba, 0x3d, 0xcc, 0xd0, 0x2e, 0x7e, 0x0e,
	0xcf, 0x52, 0x32, 0xf4, 0x9e, 0x24, 0xab, 0x6a, 0x7a, 0x52, 0xfb, 0xe3, 0xbb, 0xe0, 0x0c, 0x21,
	0xe9, 0x24, 0x6d, 0x8c, 0xc4, 0x8b, 0xe4, 0x3f, 0xe3, 0x1c, 0x08, 0x32, 0xca, 0x48, 0xc7, 0x69,
	0xaf, 0x39, 0x1a, 0xdd, 0x11, 0x5c, 0x41, 0x19, 0xe9, 0x5b, 0xd8, 0x4f, 0x1d, 0xe0, 0x01, 0x55,
	0x80, 0x87, 0xde, 0x4a, 0x0b, 0xfa, 0x4b, 0xab, 0xd7, 0x55, 0x85, 0x12, 0x94, 0x91, 0x8e, 0x22,
	0xc3, 0xc4, 0x64, 0x8f, 0xe4, 0x6b, 0x28, 0x23, 0x91, 0x28, 0x96, 0xb4, 0xf9, 0x1e, 0xc0, 0x87,
	0xb0, 0x1f, 0xdf, 0x5c, 0x76, 0xf6, 0x6b, 0x24, 0x93, 0x36, 0xff, 0x03, 0x99, 0x13, 0x28, 0xbf,
	0x9f, 0x0a, 0x9b, 0xf9, 0x09, 0x88, 0x89, 0x41, 0xd2, 0x52, 0x54, 0xd5, 0xa8, 0x68, 0x8c, 0x25,
	0x6a, 0x25, 0x55, 0x0a, 0x7f, 0x5d, 0x15, 0x85, 0x77, 0x57, 0x45, 0xe1, 0xdf, 0xab, 0xa2, 0xf0,
	0xdb, 0x75, 0x31, 0xf3, 0xee, 0xba, 0x98, 0xf9, 0xe7, 0xba, 0x98, 0xf9, 0x31, 0xef, 0xfd, 0xc3,
	0xfe, 0xfa, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0x31, 0xf1, 0x6b, 0x5a, 0x76, 0x0b, 0x00, 0x00,
}

func (m *Header) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Header) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Sign != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintGame_Common(dAtA, i, uint64(m.Sign))
	}
	return i, nil
}

func (m *KeepAliveMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KeepAliveMessage) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Header != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintGame_Common(dAtA, i, uint64(m.Header.Size()))
		n1, err1 := m.Header.MarshalTo(dAtA[i:])
		if err1 != nil {
			return 0, err1
		}
		i += n1
	}
	if len(m.Session) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintGame_Common(dAtA, i, uint64(len(m.Session)))
		i += copy(dAtA[i:], m.Session)
	}
	return i, nil
}

func (m *KeepAliveMessageResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KeepAliveMessageResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Header != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintGame_Common(dAtA, i, uint64(m.Header.Size()))
		n2, err2 := m.Header.MarshalTo(dAtA[i:])
		if err2 != nil {
			return 0, err2
		}
		i += n2
	}
	if m.RetCode != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintGame_Common(dAtA, i, uint64(m.RetCode))
	}
	if len(m.ErrorMsg) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintGame_Common(dAtA, i, uint64(len(m.ErrorMsg)))
		i += copy(dAtA[i:], m.ErrorMsg)
	}
	return i, nil
}

func (m *ProxyNotifyRechargeScoreMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProxyNotifyRechargeScoreMessage) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Header != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintGame_Common(dAtA, i, uint64(m.Header.Size()))
		n3, err3 := m.Header.MarshalTo(dAtA[i:])
		if err3 != nil {
			return 0, err3
		}
		i += n3
	}
	if m.UserId != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintGame_Common(dAtA, i, uint64(m.UserId))
	}
	if m.Id != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintGame_Common(dAtA, i, uint64(m.Id))
	}
	if len(m.OrderId) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintGame_Common(dAtA, i, uint64(len(m.OrderId)))
		i += copy(dAtA[i:], m.OrderId)
	}
	if m.RealPay != 0 {
		dAtA[i] = 0x29
		i++
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.RealPay))))
		i += 8
	}
	if m.Status != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintGame_Common(dAtA, i, uint64(m.Status))
	}
	return i, nil
}

func (m *ProxyNotifyShutDownUserClientMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProxyNotifyShutDownUserClientMessage) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Header != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintGame_Common(dAtA, i, uint64(m.Header.Size()))
		n4, err4 := m.Header.MarshalTo(dAtA[i:])
		if err4 != nil {
			return 0, err4
		}
		i += n4
	}
	if m.UserId != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintGame_Common(dAtA, i, uint64(m.UserId))
	}
	return i, nil
}

func (m *ProxyNotifyKillBossMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProxyNotifyKillBossMessage) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Header != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintGame_Common(dAtA, i, uint64(m.Header.Size()))
		n5, err5 := m.Header.MarshalTo(dAtA[i:])
		if err5 != nil {
			return 0, err5
		}
		i += n5
	}
	if len(m.Msg) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintGame_Common(dAtA, i, uint64(len(m.Msg)))
		i += copy(dAtA[i:], m.Msg)
	}
	return i, nil
}

func (m *ProxyNotifyReenterRoomMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProxyNotifyReenterRoomMessage) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Header != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintGame_Common(dAtA, i, uint64(m.Header.Size()))
		n6, err6 := m.Header.MarshalTo(dAtA[i:])
		if err6 != nil {
			return 0, err6
		}
		i += n6
	}
	return i, nil
}

func (m *HallNotifyReLoginServerMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HallNotifyReLoginServerMessage) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Header != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintGame_Common(dAtA, i, uint64(m.Header.Size()))
		n7, err7 := m.Header.MarshalTo(dAtA[i:])
		if err7 != nil {
			return 0, err7
		}
		i += n7
	}
	return i, nil
}

func encodeVarintGame_Common(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Header) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Sign != 0 {
		n += 1 + sovGame_Common(uint64(m.Sign))
	}
	return n
}

func (m *KeepAliveMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Header != nil {
		l = m.Header.Size()
		n += 1 + l + sovGame_Common(uint64(l))
	}
	l = len(m.Session)
	if l > 0 {
		n += 1 + l + sovGame_Common(uint64(l))
	}
	return n
}

func (m *KeepAliveMessageResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Header != nil {
		l = m.Header.Size()
		n += 1 + l + sovGame_Common(uint64(l))
	}
	if m.RetCode != 0 {
		n += 1 + sovGame_Common(uint64(m.RetCode))
	}
	l = len(m.ErrorMsg)
	if l > 0 {
		n += 1 + l + sovGame_Common(uint64(l))
	}
	return n
}

func (m *ProxyNotifyRechargeScoreMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Header != nil {
		l = m.Header.Size()
		n += 1 + l + sovGame_Common(uint64(l))
	}
	if m.UserId != 0 {
		n += 1 + sovGame_Common(uint64(m.UserId))
	}
	if m.Id != 0 {
		n += 1 + sovGame_Common(uint64(m.Id))
	}
	l = len(m.OrderId)
	if l > 0 {
		n += 1 + l + sovGame_Common(uint64(l))
	}
	if m.RealPay != 0 {
		n += 9
	}
	if m.Status != 0 {
		n += 1 + sovGame_Common(uint64(m.Status))
	}
	return n
}

func (m *ProxyNotifyShutDownUserClientMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Header != nil {
		l = m.Header.Size()
		n += 1 + l + sovGame_Common(uint64(l))
	}
	if m.UserId != 0 {
		n += 1 + sovGame_Common(uint64(m.UserId))
	}
	return n
}

func (m *ProxyNotifyKillBossMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Header != nil {
		l = m.Header.Size()
		n += 1 + l + sovGame_Common(uint64(l))
	}
	l = len(m.Msg)
	if l > 0 {
		n += 1 + l + sovGame_Common(uint64(l))
	}
	return n
}

func (m *ProxyNotifyReenterRoomMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Header != nil {
		l = m.Header.Size()
		n += 1 + l + sovGame_Common(uint64(l))
	}
	return n
}

func (m *HallNotifyReLoginServerMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Header != nil {
		l = m.Header.Size()
		n += 1 + l + sovGame_Common(uint64(l))
	}
	return n
}

func sovGame_Common(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozGame_Common(x uint64) (n int) {
	return sovGame_Common(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Header) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGame_Common
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Header: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Header: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sign", wireType)
			}
			m.Sign = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame_Common
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sign |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGame_Common(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGame_Common
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGame_Common
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *KeepAliveMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGame_Common
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KeepAliveMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KeepAliveMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Header", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame_Common
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGame_Common
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGame_Common
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Header == nil {
				m.Header = &Header{}
			}
			if err := m.Header.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Session", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame_Common
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGame_Common
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGame_Common
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Session = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGame_Common(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGame_Common
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGame_Common
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *KeepAliveMessageResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGame_Common
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KeepAliveMessageResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KeepAliveMessageResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Header", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame_Common
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGame_Common
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGame_Common
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Header == nil {
				m.Header = &Header{}
			}
			if err := m.Header.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RetCode", wireType)
			}
			m.RetCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame_Common
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RetCode |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrorMsg", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame_Common
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGame_Common
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGame_Common
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ErrorMsg = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGame_Common(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGame_Common
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGame_Common
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProxyNotifyRechargeScoreMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGame_Common
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProxyNotifyRechargeScoreMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProxyNotifyRechargeScoreMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Header", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame_Common
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGame_Common
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGame_Common
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Header == nil {
				m.Header = &Header{}
			}
			if err := m.Header.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserId", wireType)
			}
			m.UserId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame_Common
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UserId |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame_Common
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame_Common
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGame_Common
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGame_Common
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrderId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field RealPay", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.RealPay = float64(math.Float64frombits(v))
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame_Common
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGame_Common(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGame_Common
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGame_Common
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProxyNotifyShutDownUserClientMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGame_Common
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProxyNotifyShutDownUserClientMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProxyNotifyShutDownUserClientMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Header", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame_Common
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGame_Common
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGame_Common
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Header == nil {
				m.Header = &Header{}
			}
			if err := m.Header.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserId", wireType)
			}
			m.UserId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame_Common
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UserId |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGame_Common(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGame_Common
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGame_Common
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProxyNotifyKillBossMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGame_Common
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProxyNotifyKillBossMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProxyNotifyKillBossMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Header", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame_Common
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGame_Common
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGame_Common
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Header == nil {
				m.Header = &Header{}
			}
			if err := m.Header.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msg", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame_Common
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGame_Common
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGame_Common
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Msg = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGame_Common(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGame_Common
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGame_Common
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProxyNotifyReenterRoomMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGame_Common
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProxyNotifyReenterRoomMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProxyNotifyReenterRoomMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Header", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame_Common
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGame_Common
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGame_Common
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Header == nil {
				m.Header = &Header{}
			}
			if err := m.Header.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGame_Common(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGame_Common
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGame_Common
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HallNotifyReLoginServerMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGame_Common
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HallNotifyReLoginServerMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HallNotifyReLoginServerMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Header", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame_Common
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGame_Common
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGame_Common
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Header == nil {
				m.Header = &Header{}
			}
			if err := m.Header.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGame_Common(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGame_Common
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGame_Common
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGame_Common(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGame_Common
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGame_Common
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGame_Common
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGame_Common
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthGame_Common
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowGame_Common
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipGame_Common(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthGame_Common
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthGame_Common = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGame_Common   = fmt.Errorf("proto: integer overflow")
)
